export const SUBSCRIPTION_REQUEST = 'SUBSCRIPTION_REQUEST'
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS'
export const SUBSCRIPTION_FAILURE = 'SUBSCRIPTION_FAILURE'
export const RE_GENERATE_SUBSCRIPTION_KEY_REQUEST ="RE_GENERATE_SUBSCRIPTION_KEY_REQUEST"