export const PROJECT_REQUEST = 'PROJECT_REQUEST'
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS'
export const PROJECT_FAILURE = 'PROJECT_FAILURE'

export const PROJECT_COUNT_REQUEST = 'PROJECT_COUNT_REQUEST'
export const PROJECT_COUNT_SUCCESS = 'PROJECT_COUNT_SUCCESS'
export const PROJECT_COUNT_FAILURE = 'PROJECT_COUNT_FAILURE'
